import Banner from "@/components/pages/homeThree/Banner";
import MusicShow from "@/components/pages/homeThree/MusicShow";
import { Metadata } from "next";
import Podcast from "../../components/pages/homeThree/Podcast";

export const metadata: Metadata = {
  title: "Home Three | Online Radio NextJs Template",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <Banner />
      <Podcast />
      <MusicShow />
    </>
  );
};

export default page;
