import UpCommingShow from "@/components/pages/about/UpCommingShow";
import SubscribeNewsLetter from "@/components/pages/home-1/SubscribeNewsLetter";
import PageBanner from "@/components/shared/PageBanner";
import PodcastSchedule from "@/components/shared/PodcastSchedule";
import PreviousShows from "@/components/shared/PreviousShows";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Show Schedule | Online Radio NextJs Template",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <PageBanner pageTitle="Show Schedule" />
      <PodcastSchedule />
      <PreviousShows />
      <UpCommingShow />
      <SubscribeNewsLetter />
    </>
  );
};

export default page;
