import Contact from "@/components/contactUs/Contact";
import ContactInfo from "@/components/contactUs/ContactInfo";
import SubscribeNewsLetter from "@/components/pages/home-1/SubscribeNewsLetter";
import PageBanner from "@/components/shared/PageBanner";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact Us | Online Radio NextJs Template",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <PageBanner pageTitle="Contact Us" />
      <ContactInfo />
      <Contact />
      <SubscribeNewsLetter />
    </>
  );
};

export default page;
