import SubscribeNewsLetter from "@/components/pages/home-1/SubscribeNewsLetter";
import JoinSponsor from "@/components/pages/sponsor/JoinSponsor";
import PageBanner from "@/components/shared/PageBanner";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sponsor | Online Radio NextJs Template",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <PageBanner pageTitle="Sponsor" />
      <JoinSponsor />
      <SubscribeNewsLetter />
    </>
  );
};

export default page;
